blank_issues_enabled: false
contact_links:
  - name: Ask a question on Discussions
    url: https://github.com/YadrielPereyra/file-manager-api/discussions
    about: Please ask questions in the Discussions section.
